### ISSUE TITLE
Library 

### ISSUE THREAD

**Issue by NguyenTHYen** [VidaGIS/1091#1]
1. Ở Internal không hiển thị dữ liệu của library
2. Khi Editor tạo 1 bài viết và yêu cầu public, publisher trả lại bài viết cho editor để biên tập lại. Ở bảng Recompile document, chọn chức năng edit bào viết -> sen to publish -> không gửi được và vẫn ở trạng thái **Recompile document**

**Comment by VidaGIS** [comment]
Ở Internal không hiển thị dữ liệu của library: **Hạnh fix bug**
Khi Editor tạo 1 bài viết và yêu cầu public, publisher trả lại bài viết cho editor để biên tập lại. Ở bảng Recompile document, chọn chức năng edit bào viết -> sen to publish -> không gửi được và vẫn ở trạng thái Recompile document: Giang fix bug

**Comment by giang-dh** [comment]
lỗi số 2 - đã **fix**

**Comment by hanhvuvd** [comment]
Lỗi 1 đã fix
