### ISSUE TITLE
Hiển thị real time measurement

### ISSUE THREAD

**Issue by NguyenTHYen** [VidaGIS/1091#27]
Đăng nhập với quyền admin và khách, chọn Re Maps -> real time measurement-> chọn tỉnh thành cần xem-> không hiên thị được bản đồ.

**Comment by giang-dh** [comment]
e tag a Sơn vào, phần này của a Sơn

**Comment by NguyenTHYen** [comment]
Với khách -> zoom được tới tỉnh đã chọn
Với admin -> không zoom được tới tỉnh đã chọn
