### ISSUE TITLE
Home - Library - Sự khác biệt được đánh dấu như trong ảnh đính kèm

### ISSUE THREAD

**Issue by antt** [VidaGIS/1091#47]
![image](https://user-images.githubusercontent.com/19400596/28701481-b069e8e8-7380-11e7-8dc5-495d957cbecf.png)

**Comment by NguyenTHYen** [comment]
Tại sao ở cột Retechnology có link và sắp xếp, các cột khác không có

**Comment by hanhvuvd** [comment]
Yêu Cầu chỉ có cột đó nạ, còn cột nào nữa hay ko thì anh ko biết, chỉ biết là thời điểm hiện tại chỉ sắp xếp mỗi cột đó thôi.

**Comment by NguyenTHYen** [comment]
còn đường link thì sao anh?

**Comment by hanhvuvd** [comment]
link đó nó chỉ cho em biết để em click vào nó, và nó có sắp xếp
