### ISSUE TITLE
Cần fix lại tỉ lệ hiển thị ở Home: ReMaps

### ISSUE THREAD

**Issue by NguyenTHYen** [VidaGIS/1091#82]
![1](https://user-images.githubusercontent.com/27191815/29444365-4eba706a-8409-11e7-8fd6-95a5120e7880.PNG)

**Comment by VidaGIS** [comment]
![image](https://user-images.githubusercontent.com/17639261/29503558-c51886b0-8662-11e7-8544-3e3dbcf31fed.png)
để tạm thế này vậy

**Comment by NguyenTHYen** [comment]
vâng ạ
